---
# file: tasks/config.yml

- name: config - create ca certificate directory
  file: path="{{beats_ca_path|regex_replace('/[^/]*$', '')}}/" state=directory mode=0755

- name: config - create ca certificate
  when: beats_ca_cert != None
  copy:
    content: "{{beats_ca_cert}}"
    dest: "{{beats_ca_path}}"
    owner: root
    group: root
    mode: 0400

- name: config - create beats configuration directory
  with_items: "{{beats|default([])}}"
  file: path="/etc/{{item}}/" state=directory mode=0755

- name: config - create beats configuration
  with_items: "{{beats|default([])}}"
  template:
    src: "{{item}}.yml.j2"
    dest: "/etc/{{item}}/{{item}}.yml"
  register: beats_handler_notify
  notify:
    - log open files
    - restart service

- name: config - debug
  debug: msg="{{beats_handler_notify}}"
  when: beats_debug|default(false)

- name: config - update file /etc/hosts
  with_items: "{{beats_hosts|default([])}}"
  lineinfile: dest="/etc/hosts" state={{item.state}} line="{{item.line}}"

