---
# file: tasks/config.yml

- name: create ca certificate
  copy:
    content: "{{ beats_ca_cert }}"
    dest: "{{ beats_ca_path }}"
    owner: root
    group: root
    mode: 0400
  when: beats_ca_cert != None
  become: yes

- name: create beats configuration
  template:
    src: "{{ item }}.yml.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
  become: yes
  notify:
    - restart {{ item }}
  with_items: "{{beats_package}}"
