---
# file: tasks/config.yml

- name: config - create ca certificate
  when: beats_ca_cert != None
  copy:
    content: "{{beats_ca_cert}}"
    dest: "{{beats_ca_path}}"
    owner: root
    group: root
    mode: 0400

- name: config - create beats configuration
  with_items: "{{beats|default([])}}"
  template:
    src: "{{item}}.yml.j2"
    dest: "/etc/{{item}}/{{item}}.yml"
  notify:
    - trace open files
    - restart {{item}}

- name: config - update file /etc/hosts
  with_items: "{{beats_hosts|default([])}}"
  lineinfile: dest="/etc/hosts" state={{item.state}} line="{{item.line}}"

