---
# file: tasks/install_fedora-5.yml
# filebeat need at least a 2.6.18-194.26.1.el5 kernel to start
# on kernel-2.6.15-1.2054_FC5 filebeat will fail with beat.go:140: CRIT open /proc/sys/kernel/hostname: errno 530
# on kernel v2.6.18-194.26.1.el5 filebeat-god segfaults, so we need to monitor the filebeat process with another solution

- include: install_common.yml

- name: install - download rpm
  with_items: "{{beats_download|default([])}}"
  get_url: url="{{beats_download_url}}/{{item.name}}/{{item.name}}-{{item.version}}-{{ansible_machine}}.rpm" dest="/tmp/{{item.name}}-{{item.version}}-{{ansible_machine}}.rpm" mode=0440 validate_certs=false

- name: install - install rpm
  with_items: "{{beats_download|default([])}}"
  when: item.state|default('present') == "present"
  raw: "rpm --nosignature -qi {{item.name}} >/dev/null 2>&1 || rpm -i --nosignature /tmp/{{item.name}}-{{item.version}}-{{ansible_machine}}.rpm"

- name: install - upgrade rpm
  with_items: "{{beats_download|default([])}}"
  when: item.state|default('present') == "latest"
  raw: "rpm -i --nosignature --force /tmp/{{item.name}}-{{item.version}}-{{ansible_machine}}.rpm"

- name: install - erase rpm
  with_items: "{{beats_download|default([])}}"
  when: item.state|default('present') == "absent"
  raw: "rpm --nosignature -qi {{item.name}} >/dev/null && rpm -e {{item.name}}"

- name: install - update filebeat init script
  raw: "[ -f /etc/init.d/filebeat ] && sed -i '/daemon $daemonopts $wrapper $wrapperopts -- $agent $args/,/RETVAL=$?/{s/daemon $daemonopts $wrapper $wrapperopts -- $agent $args/rh_status_q \\&\\& success \\&\\& echo \\&\\& return\\n    exec $agent $args \\&/;s/RETVAL=$?/RETVAL=$?\\n    [ \"$RETVAL\" = 0 ] \\&\\& echo $! > ${pidfile} \\&\\& success \\|\\| failure/}; s/$pidopts $wrapper/$pidopts $agent/; /^wrapper/d' /etc/init.d/filebeat"

- name: install - remove rpm
  with_items: "{{beats_download|default([])}}"
  raw: "rm /tmp/{{item.name}}-{{item.version}}-{{ansible_machine}}.rpm"

