---
# file: tasks/install_redhat.yml

- include: install_common.yml

- name: install - add beats repository gpg key
  rpm_key:
    key: "{{beats_repository_gpg_key_url}}"
  become: yes

- name: install - add beats repository
  yumrepo:
    name: beats
    baseurl: "{{beats_repository_url}}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{beats_repository_gpg_key_url}}"
  become: yes

- name: install - install beats package from repository
  with_items: "{{beats_package}}"
  yum:
    name: "{{item.name}}"
    state: "{{item.state}}"
  notify:
    - trace open files
    - restart {{item.name}}
  become: yes

- name: install - install selected version of beats package
  with_items: "{{beats_download|default([])}}"
  yum:
    name: "{{beats_download_url}}/{{item.name}}/{{item.name}}-{{item.version}}-{{ansible_machine}}.rpm"
  notify:
    - trace open files
    - restart {{item.name}}
  become: yes

