---
# file: tasks/install.yml

- name: install - extract beats tarball
  with_items: "{{beats_download|default([])}}"
  unarchive: src="{{beats_download_url}}/{{item.name}}/{{item.name}}-{{item.version}}-{{ansible_machine}}.tar.gz" dest=/usr/local/bin remote_src=yes validate_certs=false

