---
# file: tasks/install_common.yml

- name: install - copy debug tool to trace open files
  when: hostvars[inventory_hostname]['beats_trace_filebeat'] or hostvars[inventory_hostname]['beats_trace_topbeat']
  copy:
    src: files/tmp/log-open-files
    dest: /tmp
    owner: root
    group: root
    mode: 0755

- name: install - copy debug tool to count deleted open files
  copy:
    src: files/tmp/count-deleted-open-files
    dest: /tmp
    owner: root
    group: root
    mode: 0755

- name: install - set init.d environment variables
  with_items: "{{beats_environment|default([])}}"
  when: ansible_service_mgr != "systemd"
  lineinfile:
    dest: "{{beats_init_config_directory}}/{{item.name}}"
    line: "export {{item.line}}"
    state: "{{item.state}}"
    create: yes
    owner: root
    group: root
    mode: 0644

- name: install - set systemd environment variables
  with_items: "{{beats_environment|default([])}}"
  when: ansible_service_mgr == "systemd"
  lineinfile:
    dest: "/lib/systemd/system/{{item.name}}.service"
    line: "ExecStartPre=/bin/bash -c \"/bin/systemctl set-environment {{item.line|regex_replace('\"','\\\"')}}\""
    state: "{{item.state}}"
    insertbefore: ^ExecStart
    create: no

- name: install - install a crontab to restart beats every hours
  with_items: "{{beats|default([])}}"
  lineinfile:
    dest: "/etc/cron.d/{{item}}"
    line: "0 * * * *   root    sleep 1 && /etc/init.d/{{item}} restart"
    state: "{{ hostvars[inventory_hostname]['beats_restart_' + item]|ternary('present','absent') }}"
    create: yes
    owner: root
    group: root
    mode: 0644

- name: install - install a crontab to trace beats open files
  with_items: "{{beats|default([])}}"
  lineinfile:
    dest: "/etc/cron.d/{{item}}"
    line: "0 * * * *   root    [ -x /tmp/log-open-files ] && /tmp/log-open-files {{item}}"
    state: "{{ hostvars[inventory_hostname]['beats_trace_' + item]|ternary('present','absent') }}"
    insertbefore: BOF
    create: yes
    owner: root
    group: root
    mode: 0644

