---
# file: tasks/install.yml

- name: extract beats tarball
  unarchive: src="https://download.elastic.co/beats/{{item}}/{{item}}-{{beats_{{item}}_version}}-{{ansible_machine}}.tar.gz" dest=/usr/local/bin remote_src=yes validate_certs=false
  with_items: "{{beats_package}}"

