---
# file: tasks/install_redhat.yml

- name: add beats repository gpg key
  rpm_key:
    key: "{{beats_repository_gpg_key_url}}"
  become: yes

- name: add beats repository
  yumrepo:
    name: beats
    baseurl: "{{beats_repository_url}}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{beats_repository_gpg_key_url}}"
  become: yes

- name: install beats package
  yum:
    name: "{{item.name}}"
    state: "{{item.state}}"
  notify:
    - restart {{item.name}}
  become: yes
  with_items: "{{beats_package_state}}"
