---
# file: tasks/install_debian.yml

- name: add beats repository gpg key
  apt_key:
    url: "{{beats_repository_gpg_key_url}}"
  become: yes

- name: add beats repository
  apt_repository:
    repo: "{{beats_repository_url}}"
    state: present
    update_cache: yes
  become: yes

- name: install beats package
  apt:
    name: "{{item.name}}"
    state: "{{item.state}}"
  become: yes
  notify:
    - restart {{item.name}}
  with_items: "{{beats_package_state}}"
