---
# file: tasks/install_redhat.yml

- include: install_version.yml
# - name: install - get beats installed version
#   with_items: "{{beats|default([])}}"
#   command: "rpm --nosignature -q {{item}} --queryformat=\"%{VERSION}\""
#   register: beats_version_command

- name: install - add beats repository gpg key
  rpm_key:
    key: "{{beats_repository_gpg_key_url}}"
    validate_certs: "no"
  become: yes

- name: install - add beats repository
  yumrepo:
    name: beats
    baseurl: "{{beats_repository_url}}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{beats_repository_gpg_key_url}}"
  become: yes

- name: install - install beats package from repository
  with_items: "{{beats_package|default([])}}"
  when: item.name is defined
  yum:
    name: "{{item.name}}"
    state: "{{item.state|default('present')}}"
  register: beats_handler_notify
  notify:
    - log open files
    - restart service
  become: yes

- name: install - install beats package from specific url
  with_items: "{{beats_download|default([])}}"
  yum:
    name: "{{beats_download_url}}/{{item.name}}/{{item.name}}-{{item.version}}-{{ansible_machine}}.rpm"
    state: "{{item.state|default('present')}}"
  register: beats_handler_notify
  notify:
    - log open files
    - restart service
  when: beats_version[item.name] != item.version
  become: yes

- include: install_common.yml
  become: yes

