---
# file: tasks/install_common.yml

- name: install - copy debug tool to trace open files
  copy:
    src: files/tmp/open-files
    dest: /tmp
    owner: root
    group: root
    mode: 0755
  become: yes

- name: install - set init.d environment variables
  with_items: "{{beats_environment}}"
  lineinfile:
    dest: "/etc/sysconfig/{{item.name}}"
    line: "export {{item.line}}"
    state: "{{item.state}}"
    create: yes
    owner: root
    group: root
    mode: 0644
  become: yes

- name: install - set systemd environment variables
  with_items: "{{beats_environment}}"
  lineinfile:
    dest: "/lib/systemd/system/{{item.name}}.service"
    line: "ExecStartPre=/bin/bash -c \"/bin/systemctl set-environment {{item.line|regex_replace('\"','\\\"')}}\""
    state: "{{item.state}}"
    insertbefore: ^ExecStart
    create: no
  become: yes

- name: install - install a crontab to restart beats every day
  with_items: "{{beats_crontab}}"
  lineinfile:
    dest: "/etc/cron.d/{{item.name}}"
    line: "0 * * * *   root    sleep 1 && /etc/init.d/{{item.name}} restart"
    state: "{{item.crontab|ternary('present','absent')}}"
    create: yes
    owner: root
    group: root
    mode: 0644
  become: yes

- name: install - install a crontab to trace beats open files
  with_items: "{{beats_crontab}}"
  lineinfile:
    dest: "/etc/cron.d/{{item.name}}"
    line: "0 * * * *   root    [ -x /tmp/open-files ] && /tmp/open-files {{item.name}}"
    state: "{{item.crontab|ternary('present','absent')}}"
    insertbefore: BOF
    create: yes
    owner: root
    group: root
    mode: 0644
  become: yes
  when: "beats_trace_{{item.name}}"

