---
# file: tasks/install_debian.yml

- include: install_version.yml
# - name: install - get beats installed version
#   with_items: "{{beats|default([])}}"
#   command: "dpkg-query --showformat='${Version}' --show {{item}}"
#   register: beats_version_command
#   ignore_errors: yes

- name: install - add beats repository gpg key
  apt_key:
    url: "{{beats_repository_gpg_key_url}}"
    validate_certs: "no"
  become: yes

- name: install - add beats repository
  apt_repository:
    repo: "{{beats_repository_url}}"
    state: present
    update_cache: yes
  become: yes

- name: install - install beats package from repository
  with_items: "{{beats_package|default([])}}"
  when: item.name is defined
  apt:
    name: "{{item.name}}=''{{item.version|default('')}}"
    state: "{{item.state|default('present')}}"
  become: yes
  register: beats_handler_notify
  notify:
    - log open files
    - restart service

- name: install - install selected version of beats package
  with_items: "{{beats_download|default([])}}"
  apt:
    deb: "{{beats_download_url}}/{{item.name}}/{{item.name}}-{{item.version}}-{{ansible_architecture|regex_replace('x86_64', 'amd64')}}.deb"
    state: "{{item.state|default('present')}}"
  register: beats_handler_notify
  notify:
    - log open files
    - restart service
  when: beats_version[item.name] != item.version
  become: yes

- include: install_common.yml
  become: yes

