---
- name: add elastic gpg key
  apt_key:
    url: "{{ filebeat_gpg_url }}"
  become: yes

- name: add beats repository
  apt_repository:
    repo: "{{ filebeat_apt_repo }}"
    state: present
    update_cache: yes
  become: yes

- name: install filebeat
  apt:
    name: filebeat
    state: "{{ filebeat_package_state }}"
  become: yes
  notify:
    - restart filebeat
