---
# file: tasks/service_fedora-5.yml

- name: service - register monit status
  command: "which monit"
  register: beats_monit
  failed_when: false

- name: service - download monit rpm
  get_url: url="http://ftp.pbone.net/mirror/dries.studentenweb.org/apt/fedora/fc5/{{ansible_architecture}}/RPMS.dries/monit-4.9-2.fc5.rf.{{ansible_architecture}}.rpm" dest="/tmp/monit-{{ansible_architecture}}.rpm" mode=0440 validate_certs=false
  when: beats_monit.stdout == ""

- name: service - install monit rpm
  raw: "rpm -qi monit >/dev/null 2>&1 || rpm -i /tmp/monit-{{ansible_architecture}}.rpm"
  when: beats_monit.stdout == ""

- name: service - remove monit rpm
  raw: "rm /tmp/monit-{{ansible_architecture}}.rpm"
  when: beats_monit.stdout == ""

- name: service - update monit init script
  raw: "[ -f /etc/init.d/monit ] && sed -i 's/daemon $prog -c \"$CONFIG\"/daemon $prog -d 1 -c \"$CONFIG\"/' /etc/init.d/monit"
  when: beats_monit.stdout == ""

- name: service - disable beats services
  with_items: "{{beats}}"
  service:
    name: "{{item}}"
    state: "stopped"
    enabled: false

- include: service_monit.yml

