---
# file: tasks/service_fedora-5.yml

- name: service - download monit rpm
  get_url: url="http://ftp.pbone.net/mirror/dries.studentenweb.org/apt/fedora/fc5/{{ansible_architecture}}/RPMS.dries/monit-4.9-2.fc5.rf.{{ansible_architecture}}.rpm" dest="/tmp/monit-{{ansible_architecture}}.rpm" mode=0440 validate_certs=false

- name: service - install monit rpm
  raw: "rpm -qi monit >/dev/null 2>&1 || rpm -i /tmp/monit-{{ansible_architecture}}.rpm"

- name: service - remove monit rpm
  raw: "rm /tmp/monit-{{ansible_architecture}}.rpm"

- name: service - configure monit for filebeat
  copy: src=../files/etc/monit.d/filebeat dest=/etc/monit.d/filebeat owner=root group=root mode=0644

- name: service - configure monit alert mail
  raw: "[ -f /etc/centile/cluster/cluster.conf ] && { grep '^set alert' /etc/monit.conf >/dev/null 2>&1 || awk 'BEGIN {FS=\"=\"} $0 ~ /^mail_recipient/ {print \"set alert \"$2}' /etc/centile/cluster/cluster.conf >> /etc/monit.conf; } || true"

- name: service - update monit init script
  raw: "[ -f /etc/init.d/monit ] && sed -i 's/daemon $prog -c \"$CONFIG\"/daemon $prog -d 1 -c \"$CONFIG\"/' /etc/init.d/monit"

- name: service - start and enable monit
  service:
    name: monit
    state: "{{beats_start_filebeat |default(true) |ternary('started','stopped')}}"
    enabled: "{{beats_start_filebeat |default(true)}}"

- name: service - disable beats services
  with_items: "{{beats}}"
  service:
    name: "{{item}}"
    state: "stopped"
    enabled: false

