---
# file: tasks/service.yml

- name: service - install monit
  package:
    name: "monit"
    state: "present"

- name: service - copy beats init script
  with_items: "{{beats|default([])}}"
  copy:
    src: ../files/etc/init.d/beats
    dest: "/etc/init.d/{{item}}"
    mode: 0755
    owner: root
    group: root

- include: service_monit.yml
