#!/bin/sh
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
[ -n "$1" ] || exit

PID=$(pidof "$1")
for pid in $PID; do
  let $pid >/dev/null 2>&1 || continue
  [ -d /tmp/$1 ] || mkdir -p /tmp/$1
  file="/tmp/$1/open-files-$(date +%Y%m%d_%H%M%S)-${pid}.log"
  echo "# ps auwwx |grep -v $0 |grep $1 |grep -v grep" > $file
  ps auwwx |grep -v $0 |grep $1 |grep -v grep >> $file
  echo "# tail /tmp/$1/$1.out 2>/dev/null" >> $file
  [ -f "/tmp/$1/$1.out" ] && tail /tmp/$1/$1.out 2>/dev/null >> $file
  echo "# lsof -p $pid 2>/dev/null" >> $file
  lsof -p $pid 2>/dev/null ||true >> $file
done
