---
# file: handlers/main.yml

- name: trace open files
  with_items: "{{beats}}"
  command: /tmp/deleted-files "{{item}}"
  when: "beats_trace_{{item}}"
  become: yes

- name: restart filebeat
  service:
    name: filebeat
    state: restarted
  become: yes

- name: restart topbeat
  service:
    name: topbeat
    state: restarted
  become: yes

