---
# file: handlers/main.yml

- name: trace open files
  with_items: "{{beats}}"
  command: "/tmp/open-files {{item}}"
  when: "beats_trace_{{item}}"

- name: restart filebeat
  service:
    name: filebeat
    state: restarted

- name: restart topbeat
  service:
    name: topbeat
    state: restarted

