---
# file: handlers/main.yml

- name: log open files
  with_items: "{{beats_handler_notify.results}}"
  command: "/tmp/log-open-files {{item.item}}"
  when: item.changed and beats_trace_{{item.item}}|default(false)

- name: restart service
  with_items: "{{beats_handler_notify.results}}"
  service:
    name: "{{item.item}}"
    state: restarted
  when: item.changed and beats_start_{{item.item}}|default(true)

